### ISSUE TITLE
OrthoFinder fails to find expected Newick tree

### ISSUE THREAD

**Issue by davidjstudholme** [rhysf/Synima#12]
When I run ```Orthologs_to_summary.pl```, it fails to generate the ```all_orthomcl.out```file. The clue to the failure seems to be this message in the output:
```
Running Orthofinder...
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1610, in <module>
  File "orthofinder/orthofinder.py", line 1429, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 1097, in OrthologuesWorkflow
  File "orthofinder/scripts/stride.py", line 505, in GetRoot
  File "multiprocessing/pool.py", line 250, in map
  File "multiprocessing/pool.py", line 554, in get
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
Failed to execute script orthofinder
```

I cannot see any obvious Newick tree file in the  ```Orthofinder_outdir``` directory:

```
$ ls Orthofinder_outdir/
Blast0_0.txt  Blast2_0.txt  Blast4_0.txt  clusters_OrthoFinder_v2.2.7_I1.5.txt               Species1.fa
Blast0_1.txt  Blast2_1.txt  Blast4_1.txt  clusters_OrthoFinder_v2.2.7_I1.5.txt_id_pairs.txt  Species2.fa
Blast0_2.txt  Blast2_2.txt  Blast4_2.txt  OrthoFinder_v2.2.7_graph.txt                       Species3.fa
Blast0_3.txt  Blast2_3.txt  Blast4_3.txt  Orthogroups.csv                                    Species4.fa
Blast0_4.txt  Blast2_4.txt  Blast4_4.txt  Orthogroups.GeneCount.csv                          Species5.fa
Blast0_5.txt  Blast2_5.txt  Blast4_5.txt  Orthogroups_SpeciesOverlaps.csv                    SpeciesIDs.txt
Blast1_0.txt  Blast3_0.txt  Blast5_0.txt  Orthogroups.txt                                    Statistics_Overall.csv
Blast1_1.txt  Blast3_1.txt  Blast5_1.txt  Orthogroups_UnassignedGenes.csv                    Statistics_PerSpecies.csv
Blast1_2.txt  Blast3_2.txt  Blast5_2.txt  Orthologues_Oct06
Blast1_3.txt  Blast3_3.txt  Blast5_3.txt  SequenceIDs.txt
Blast1_4.txt  Blast3_4.txt  Blast5_4.txt  SingleCopyOrthogroups.txt
Blast1_5.txt  Blast3_5.txt  Blast5_5.txt  Species0.fa
```

So, which script was supposed to have generated the tree file? Where does orthofinder expect to find this tree file? Should the user provide the tree? Can the requirement for the tree be avoided?

Here is the full output from this step:

```
$ perl ./Synima/util/Blast_all_vs_all_repo_to_Orthofinder.pl -r ./Repo_spec.txt
Parsing repo spec...
Assigning genome codes...
Assigning sequence IDs and save FASTA...
fasta_id_to_seq_hash: saving sequences from ./B_lactucae_SF5/B_lactucae_SF5.annotation.pep.synima-parsed.PEP...
fasta_id_to_seq_hash: saving sequences from ./P_effusa_R14/P_effusa_R14.annotation.pep.synima-parsed.PEP...
fasta_id_to_seq_hash: saving sequences from ./Pl_halstedii/Pl_halstedii.annotation.pep.synima-parsed.PEP...
fasta_id_to_seq_hash: saving sequences from ./Ph_sojae_P6497/Ph_sojae_P6497.annotation.pep.synima-parsed.PEP...
fasta_id_to_seq_hash: saving sequences from ./P_belbahri/P_belbahri.annotation.pep.synima-parsed.PEP...
fasta_id_to_seq_hash: saving sequences from ./P_effusa_R13/P_effusa_R13.annotation.pep.synima-parsed.PEP...
retrieve_blast_pairs_orthofinder...
retrieve_hits_orthofinder: ./B_lactucae_SF5/RBH_blast_PEP/vs_B_lactucae_SF5.blast.m8 -> Orthofinder_outdir/Blast0_0.txt
retrieve_hits_orthofinder: ./B_lactucae_SF5/RBH_blast_PEP/vs_P_belbahri.blast.m8 -> Orthofinder_outdir/Blast0_4.txt
retrieve_hits_orthofinder: ./P_belbahri/RBH_blast_PEP/vs_B_lactucae_SF5.blast.m8 -> Orthofinder_outdir/Blast4_0.txt
retrieve_hits_orthofinder: ./B_lactucae_SF5/RBH_blast_PEP/vs_P_effusa_R13.blast.m8 -> Orthofinder_outdir/Blast0_5.txt
retrieve_hits_orthofinder: ./P_effusa_R13/RBH_blast_PEP/vs_B_lactucae_SF5.blast.m8 -> Orthofinder_outdir/Blast5_0.txt
retrieve_hits_orthofinder: ./B_lactucae_SF5/RBH_blast_PEP/vs_P_effusa_R14.blast.m8 -> Orthofinder_outdir/Blast0_1.txt
retrieve_hits_orthofinder: ./P_effusa_R14/RBH_blast_PEP/vs_B_lactucae_SF5.blast.m8 -> Orthofinder_outdir/Blast1_0.txt
retrieve_hits_orthofinder: ./B_lactucae_SF5/RBH_blast_PEP/vs_Ph_sojae_P6497.blast.m8 -> Orthofinder_outdir/Blast0_3.txt
retrieve_hits_orthofinder: ./Ph_sojae_P6497/RBH_blast_PEP/vs_B_lactucae_SF5.blast.m8 -> Orthofinder_outdir/Blast3_0.txt
retrieve_hits_orthofinder: ./B_lactucae_SF5/RBH_blast_PEP/vs_Pl_halstedii.blast.m8 -> Orthofinder_outdir/Blast0_2.txt
retrieve_hits_orthofinder: ./Pl_halstedii/RBH_blast_PEP/vs_B_lactucae_SF5.blast.m8 -> Orthofinder_outdir/Blast2_0.txt
retrieve_hits_orthofinder: ./P_belbahri/RBH_blast_PEP/vs_P_belbahri.blast.m8 -> Orthofinder_outdir/Blast4_4.txt
retrieve_hits_orthofinder: ./P_belbahri/RBH_blast_PEP/vs_P_effusa_R13.blast.m8 -> Orthofinder_outdir/Blast4_5.txt
retrieve_hits_orthofinder: ./P_effusa_R13/RBH_blast_PEP/vs_P_belbahri.blast.m8 -> Orthofinder_outdir/Blast5_4.txt
retrieve_hits_orthofinder: ./P_belbahri/RBH_blast_PEP/vs_P_effusa_R14.blast.m8 -> Orthofinder_outdir/Blast4_1.txt
retrieve_hits_orthofinder: ./P_effusa_R14/RBH_blast_PEP/vs_P_belbahri.blast.m8 -> Orthofinder_outdir/Blast1_4.txt
retrieve_hits_orthofinder: ./P_belbahri/RBH_blast_PEP/vs_Ph_sojae_P6497.blast.m8 -> Orthofinder_outdir/Blast4_3.txt
retrieve_hits_orthofinder: ./Ph_sojae_P6497/RBH_blast_PEP/vs_P_belbahri.blast.m8 -> Orthofinder_outdir/Blast3_4.txt
retrieve_hits_orthofinder: ./P_belbahri/RBH_blast_PEP/vs_Pl_halstedii.blast.m8 -> Orthofinder_outdir/Blast4_2.txt
retrieve_hits_orthofinder: ./Pl_halstedii/RBH_blast_PEP/vs_P_belbahri.blast.m8 -> Orthofinder_outdir/Blast2_4.txt
retrieve_hits_orthofinder: ./P_effusa_R13/RBH_blast_PEP/vs_P_effusa_R13.blast.m8 -> Orthofinder_outdir/Blast5_5.txt
retrieve_hits_orthofinder: ./P_effusa_R13/RBH_blast_PEP/vs_P_effusa_R14.blast.m8 -> Orthofinder_outdir/Blast5_1.txt
retrieve_hits_orthofinder: ./P_effusa_R14/RBH_blast_PEP/vs_P_effusa_R13.blast.m8 -> Orthofinder_outdir/Blast1_5.txt
retrieve_hits_orthofinder: ./P_effusa_R13/RBH_blast_PEP/vs_Ph_sojae_P6497.blast.m8 -> Orthofinder_outdir/Blast5_3.txt
retrieve_hits_orthofinder: ./Ph_sojae_P6497/RBH_blast_PEP/vs_P_effusa_R13.blast.m8 -> Orthofinder_outdir/Blast3_5.txt
retrieve_hits_orthofinder: ./P_effusa_R13/RBH_blast_PEP/vs_Pl_halstedii.blast.m8 -> Orthofinder_outdir/Blast5_2.txt
retrieve_hits_orthofinder: ./Pl_halstedii/RBH_blast_PEP/vs_P_effusa_R13.blast.m8 -> Orthofinder_outdir/Blast2_5.txt
retrieve_hits_orthofinder: ./P_effusa_R14/RBH_blast_PEP/vs_P_effusa_R14.blast.m8 -> Orthofinder_outdir/Blast1_1.txt
retrieve_hits_orthofinder: ./P_effusa_R14/RBH_blast_PEP/vs_Ph_sojae_P6497.blast.m8 -> Orthofinder_outdir/Blast1_3.txt
retrieve_hits_orthofinder: ./Ph_sojae_P6497/RBH_blast_PEP/vs_P_effusa_R14.blast.m8 -> Orthofinder_outdir/Blast3_1.txt
retrieve_hits_orthofinder: ./P_effusa_R14/RBH_blast_PEP/vs_Pl_halstedii.blast.m8 -> Orthofinder_outdir/Blast1_2.txt
retrieve_hits_orthofinder: ./Pl_halstedii/RBH_blast_PEP/vs_P_effusa_R14.blast.m8 -> Orthofinder_outdir/Blast2_1.txt
retrieve_hits_orthofinder: ./Ph_sojae_P6497/RBH_blast_PEP/vs_Ph_sojae_P6497.blast.m8 -> Orthofinder_outdir/Blast3_3.txt
retrieve_hits_orthofinder: ./Ph_sojae_P6497/RBH_blast_PEP/vs_Pl_halstedii.blast.m8 -> Orthofinder_outdir/Blast3_2.txt
retrieve_hits_orthofinder: ./Pl_halstedii/RBH_blast_PEP/vs_Ph_sojae_P6497.blast.m8 -> Orthofinder_outdir/Blast2_3.txt
retrieve_hits_orthofinder: ./Pl_halstedii/RBH_blast_PEP/vs_Pl_halstedii.blast.m8 -> Orthofinder_outdir/Blast2_2.txt
Running Orthofinder...
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1610, in <module>
  File "orthofinder/orthofinder.py", line 1429, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 1097, in OrthologuesWorkflow
  File "orthofinder/scripts/stride.py", line 505, in GetRoot
  File "multiprocessing/pool.py", line 250, in map
  File "multiprocessing/pool.py", line 554, in get
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
Failed to execute script orthofinder

OrthoFinder version 2.2.7 Copyright (C) 2014 David Emms

2019-10-06 13:02:33 : Starting OrthoFinder
16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /mnt/bio-surimi-data/peronospora_belbahrii/synima/Orthofinder_outdir/SimpleTest.phy -o /mnt/bio-surimi-data/peronospora_belbahrii/synima/Orthofinder_outdir/SimpleTest.tre" - ok
Using previously calculated BLAST results in /mnt/bio-surimi-data/peronospora_belbahrii/synima/Orthofinder_outdir/

Running OrthoFinder algorithm
-----------------------------
2019-10-06 13:02:33 : Initial processing of each species
2019-10-06 13:02:36 : Initial processing of species 0 complete
2019-10-06 13:02:39 : Initial processing of species 1 complete
2019-10-06 13:02:44 : Initial processing of species 2 complete
2019-10-06 13:02:56 : Initial processing of species 3 complete
2019-10-06 13:03:00 : Initial processing of species 4 complete
2019-10-06 13:03:03 : Initial processing of species 5 complete
2019-10-06 13:03:11 : Connected putatitive homologs
2019-10-06 13:03:37 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /mnt/bio-surimi-data/peronospora_belbahrii/synima/Orthofinder_outdir/Orthogroups.csv
   /mnt/bio-surimi-data/peronospora_belbahrii/synima/Orthofinder_outdir/Orthogroups.txt (OrthoMCL format)
   /mnt/bio-surimi-data/peronospora_belbahrii/synima/Orthofinder_outdir/Orthogroups_UnassignedGenes.csv
2019-10-06 13:03:38 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2019-10-06 13:04:28 : Done 0 of 7336
2019-10-06 13:04:40 : Done 1000 of 7336
2019-10-06 13:04:50 : Done 2000 of 7336
2019-10-06 13:05:00 : Done 3000 of 7336
2019-10-06 13:05:09 : Done 4000 of 7336
2019-10-06 13:05:19 : Done 5000 of 7336
2019-10-06 13:05:29 : Done 6000 of 7336
2019-10-06 13:05:39 : Done 7000 of 7336
2019-10-06 13:04:25 : Done

Inferring gene and species trees
--------------------------------

OG0001163_tree_id.txt - WARNING: ETE could not interpret tree file, it will be ignored
4531 trees had all species present and will be used by STAG to infer the species tree


Best outgroup(s) for species tree
---------------------------------
2019-10-06 13:07:56 : Starting STRIDE

Finished with: 65280
```

**Comment by davidjstudholme** [comment]
I think the problem is solved. There is no issue with your code, Rhys!

The issue was caused by my pipeline breaking at the ```Blast_all_vs_all_repo_to_Orthofinder.pll``` step.
